name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # Changelog
  $CHANGES

  See details of [all code changes](https://github.com/github/contributors/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'rota'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'docs'
      - 'debt'
      - 'tests'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

autolabeler:
  - label: 'documentation'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'rota'
    branch:
      - '/rota\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
      - '/feature\/.+/'
  - label: 'enhancement'
    branch:
      - '/enh\/.+/'
      - '/enhancement\/.+/'
  - label: 'debt'
    branch:
      - '/debt\/.+/'