name: Auto labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'release/*'
      - 'hotfix/*'

permissions:
  contents: write
  pull-requests: read

jobs:
 auto-labeler:
   runs-on: ubuntu-latest
   steps:
     - uses: release-drafter/release-drafter@v5
       with:
         disable-releaser: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
