name: Create release draft

on:
  push:
    branches:
      - 'release/*'
      - 'hotfix/*'

permissions:
  contents: write

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version
        id: extract_version
        run: |
          branch_name=${GITHUB_REF##*/}
          
          # Extract version using regex
          if [[ $branch_name =~ ^(hotfix|release)/v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            version="v${BASH_REMATCH[2]}.${BASH_REMATCH[3]}.${BASH_REMATCH[4]}"
            echo "Version: $version"
            echo "::set-output name=version::$version"
          else
            echo "Branch name does not match the expected pattern"
            exit 0
          fi

      - name: Get short commit hash
        id: get_commit_hash
        run: |
          short_commit_hash=$(git rev-parse --short HEAD)
          echo "::set-output name=short_commit_hash::$short_commit_hash"

      - name: Create tag
        id: create_tag
        run: |
          tag="${{ steps.extract_version.outputs.version }}-${{ steps.get_commit_hash.outputs.short_commit_hash }}"
          echo "Creating tag: $tag"
          git tag $tag
          git push origin $tag

      - name: Display extracted version and commit hash
        run: |
          echo "Extracted version: ${{ steps.extract_version.outputs.version }}"
          echo "Short commit hash: ${{ steps.get_commit_hash.outputs.short_commit_hash }}"

      - uses: release-drafter/release-drafter@v5
        name: Update or create release draft
        with:
          version: ${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
