name: Create release draft

on:
  push:
    branches:
      - 'release/*'
      - 'hotfix/*'

permissions:
  contents: write

jobs:
  update-release-draft:
    if: |
        (github.event_name == 'workflow_dispatch') || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version and validate semver
        id: extract_version
        run: |
          version=${GITHUB_REF##*/}

          if [[ $version =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "Version $version is valid."
            echo "::set-output name=version::$version"
          else
            echo "Invalid version format: $version"
            exit 1
          fi

      - name: Get short commit hash
        id: get_commit_hash
        run: |
          short_commit_hash=$(git rev-parse --short HEAD)
          echo "::set-output name=short_commit_hash::$short_commit_hash"

      - name: Create tag
        id: create_tag
        run: |
          tag="${{ steps.extract_version.outputs.version }}-${{ steps.get_commit_hash.outputs.short_commit_hash }}"
          echo "Creating tag: $tag"
          git tag $tag
          git push origin $tag

      - name: Display extracted version and commit hash
        run: |
          echo "Extracted version: ${{ steps.extract_version.outputs.version }}"
          echo "Short commit hash: ${{ steps.get_commit_hash.outputs.short_commit_hash }}"

      - uses: release-drafter/release-drafter@v5
        name: Update or create release draft
        with:
          version: ${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
